USE ROLE SECURITYADMIN;

-- Database level
GRANT USAGE ON DATABASE LOOTSTREAM TO ROLE KAFKA_CONNECTOR_ROLE;

-- Schema level
GRANT USAGE ON SCHEMA LOOTSTREAM.RAW TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT CREATE TABLE ON SCHEMA LOOTSTREAM.RAW TO ROLE KAFKA_CONNECTOR_ROLE;

-- Table level (insert for streaming, select for verification)
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA LOOTSTREAM.RAW TO ROLE KAFKA_CONNECTOR_ROLE;

-- Future tables too (in case connector auto-creates)
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA LOOTSTREAM.RAW TO ROLE KAFKA_CONNECTOR_ROLE;

-- Warehouse
GRANT USAGE ON WAREHOUSE LOOTSTREAM_WH TO ROLE KAFKA_CONNECTOR_ROLE;