select count(*) from LOOTSTREAM.RAW.RAW_CARD_UPGRADES
select count(*) from LOOTSTREAM.RAW.RAW_CHEST_OPENINGS
select count(*) from LOOTSTREAM.RAW.RAW_GEM_PURCHASES
select count(*) from LOOTSTREAM.RAW.RAW_PLAYER_TRADES

SELECT 'GEM' AS t, COUNT(*) FROM LOOTSTREAM.RAW.RAW_GEM_PURCHASES
UNION ALL SELECT 'UPG', COUNT(*) FROM LOOTSTREAM.RAW.RAW_CARD_UPGRADES
UNION ALL SELECT 'CHS', COUNT(*) FROM LOOTSTREAM.RAW.RAW_CHEST_OPENINGS
UNION ALL SELECT 'TRD', COUNT(*) FROM LOOTSTREAM.RAW.RAW_PLAYER_TRADES;