USE DATABASE LOOTSTREAM;
USE SCHEMA RAW;

-- Gem purchases
CREATE TABLE IF NOT EXISTS RAW_GEM_PURCHASES (
  RECORD_CONTENT VARIANT,
  RECORD_METADATA VARIANT
)
COMMENT = 'Raw gem purchase events from Kafka';

-- Card upgrades
CREATE TABLE IF NOT EXISTS RAW_CARD_UPGRADES (
  RECORD_CONTENT VARIANT,
  RECORD_METADATA VARIANT
)
COMMENT = 'Raw card upgrade events from Kafka';

-- Chest openings
CREATE TABLE IF NOT EXISTS RAW_CHEST_OPENINGS (
  RECORD_CONTENT VARIANT,
  RECORD_METADATA VARIANT
)
COMMENT = 'Raw chest opening events from Kafka';

-- Player trades
CREATE TABLE IF NOT EXISTS RAW_PLAYER_TRADES (
  RECORD_CONTENT VARIANT,
  RECORD_METADATA VARIANT
)
COMMENT = 'Raw player trade events from Kafka';